#!/bin/sh

# provest zalohu stavajici konfigurace
if [ -d /usr/local/UniFi/data ]; then
  echo "Backing up UniFi data..."
  #BACKUPFILE=/var/backups/unifi-`date +"%Y%m%d_%H%M%S"`.tgz
 
  /usr/bin/tar -vczf ${BACKUPFILE} /usr/local/UniFi/data
  else
  echo "Vlozte nazav souboru pro obnovu: "
  read sBACKUPFILE
  BACKUPFILE=/var/backups/sBACKUPFILE
fi


# Restore the backup:
if [ ! -z "${BACKUPFILE}" ] && [ -f ${BACKUPFILE} ]; then
  echo "Obnova zalohy konfigurace UniFi..."
  mv /usr/local/UniFi/data /usr/local/UniFi/data-`date +%Y%m%d-%H%M`
  /usr/bin/tar -vxzf ${BACKUPFILE} -C /
  
  echo "smazani souboru: ${BACKUPFILE}"
  #rm BACKUPFILE
fi



